### ISSUE TITLE
Suggestions by prospective math teachers of JKU/PHDL/PHOÖ

### ISSUE THREAD

**Issue by windiaar** [kovzol/aris#18]
Dear Sirs,

I would like to propose two suggestions for potential improvments of the GNU Aris program:

1. I would appreciate an interference-function for contrapositions 
For example:
Premises:
(Not B)
(A Implies B)
Right now it is necessary to use "Equivalence-Implication" to prove (Not A Or B) followed by the proof of (Not A) via "Interference-Disjunctive" while selecting both premises.

It would be convenient to use an "Interference-Contraposition"-function while selecting both premises to be able to prove (Not A) without an additional step.

2. I also suggest allowing LATEX-notation for inputs, which may be convenient for some users.

Thanks in advance and keep up the great work.

Kind Regards

**Comment by Susanna-lehner** [comment]
Sehr geehrtes Team,

ich hätte da drei Verbesserungsvorschläge für Ihr Programm.
1. Es sollte die Kommutativität der "Oder"-Operation automatisch erkennen. Jedes mal eine neue Zeile zu machen damit man auf "AvB" und "BvA" verweisen kann ist etwas mühsam. Man weis nämlich dann nicht immer gleich ob man einen Fehler in seinem Beweis hat oder ob es an diesem Problem liegt.
2. Oft wiederholen sich Teile der Beweiskette. Da wäre es praktisch, wenn man bestimmte Teile der Zeilen im Programm markieren, dann kopieren und einfügen könnte.
3. Wäre es möglich auch ein "exklusives Oder" im Programm einzuführen?

Freundliche Grüße
Susanna Lehner

**Comment by windiaar** [comment]
Dear Sirs,

I came up with further QoL-Features while working with GNU Aris:

- It would be great if one could highlight inputs (e.g. to delete/edit certain parts of the input)
- A feature for copying and pasting inputs in combination with the ability to highlight inputs would be greatly appreciated, especially when a certain part of an input has to be reused.
- Currently one is not able to change the type of input (Premise, Conclusion, ...). Therefore, accidentally picking the wrong category requires to do the same input twice. This issue could be resolved with above suggestions, it still would be helpful to change the category of input after creating a new line.

Thanks in advance and kind regards!
